CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_ZBUS=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_QEMU_ICOUNT=n

CONFIG_GPIO_EMUL=y
CONFIG_GPIO=y
CONFIG_LOG=y

CONFIG_UART_CONSOLE=y

CONFIG_NEWLIB_LIBC=y

CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

CONFIG_NEWLIB_LIBC_FLOAT_SCANF=y

CONFIG_RADAR_SPEED_LIMIT_LIGHT_KMH=80
CONFIG_RADAR_SPEED_LIMIT_HEAVY_KMH=60